### ISSUE TITLE
Unable to manual import in a swift project

### ISSUE THREAD

**Issue by MacKentoch** [derekblair/ILPDFKit#23]
# Really nice work : thanks!

But I can't import it manually in my project (mainly swift but may not be related).
- I added `ILPDFKit folder` to my project (mainly swift project)
- I already use `ARC`
- I linked 
  - `UIKit`
  - `QuartzCore`
  - `CoreGraphic` (seen it in project template)

I compare the template project and mine and don't see what is wrong.
The only difference is 
- my project mainly swift

VERSUS
- template project : Objective C

=> I don't see the problem...

---

If someone had a try one day to import it manually in swift project, tell me (_so that I will understand where I am wrong right now^^_)

**Comment by MacKentoch** [comment]
It is a shame such a nice lib, I can't import in my swift project.

If anyone had some suggestion I would greatly appreciate.

**Comment by zummenix** [comment]
Hi @MacKentoch 
Did you add bridging header file to your swift project?

**Comment by codicil** [comment]
@zummenix how to use bridging header file for this pod, I know how to add objective C header file in swift project but what line to put in the bridging header file

e.g. # import ?? 

also how to use ARC, as I am just started learning iOS my question may be of very basic kind please excuse me for that

**Comment by zummenix** [comment]
@codicil, if in your pod the line `use_frameworks!` exist, I believe you don't need to add anything in your bridging header, just `import ILPDFKit` in your swift files.

You don't need to worry about ARC at this stage.
