### ISSUE TITLE
Date select field is considered as PDFTextField

### ISSUE THREAD

**Issue by RyanKim01** [derekblair/ILPDFKit#29]
I have date select field in my PDF and ILPDFKit considers that field as PDFFormType.Text.
When I'm setting value "01/11/16" to the field in PDF, ILPDFKit converts the value and prints it out as 
"2016-01-11 01:13:36 +0000". Is there a way to just input "01/11/16" instead of "2016-01-11 01:13:36 +0000" ?

**Comment by lordgreg** [comment]
This is the exact same issue we're having. Can the somehow be fixed?

**Comment by derekblair** [comment]
Should be resolved now.
