### ISSUE TITLE
How update a checkbox (PDFFormTypeButton)???

### ISSUE THREAD

**Issue by jaouahbi** [derekblair/ILPDFKit#36]
assuming form is a PDFFormTypeButton
on =  [_pdfDocument.forms setValue:@"1" forFormWithName:form.name];??
off =  [_pdfDocument.forms setValue:@"0" forFormWithName:form.name];??
seems do not work

**Comment by Twelve57** [comment]
Try "Yes" and "No" instead of "1" and "0"

**Comment by jaouahbi** [comment]
No work :( very thanx

**Comment by jaouahbi** [comment]
Works :), thank you!

**Comment by codicil** [comment]
jaouahbi ,

 I need your help, I am a student and learning iOS, I am working on a study project, where user input will be transformed to PDF form, than save/print

I have developed the user input view, installed ILPDFKit thinking about I can programmatically send input to PDF form field (say one of the PDF form field name is first_name, I should be able to populate first name in that field entered by user programmatically, there are some checkbox as well which shall be checked programmatically based on user input) but I am really stuck with how to transfer my user input to PDF, also I am working on Swift and have no idea about objectiveC

if you would share some sample coding or a sample project, that will be awesome

 I hope I am not taking too much of your time and thanks a lot for your help

 Kindest Regards,

 Ahmed
