### ISSUE TITLE
Multi-Page PDF crashes when scrolling

### ISSUE THREAD

**Issue by stevestencil** [derekblair/ILPDFKit#38]
I have a multi-page PDF that loads the first page however as soon as I scroll up to the second page it crashes the app and logs "Collection <__NSArrayM: 0x16084c530> was mutated while being enumerated."

**Comment by SaurabhPrajapati** [comment]
any update on this? i m facing same issue on ipad , and its occur only when i input any text in textfield and than try to scroll PDF.

**Comment by stevestencil** [comment]
Luckily the client that I was building for was able to use only single page PDFs. I was unable to figure this out

**Comment by SaurabhPrajapati** [comment]
really lucky , as my client is used pdf of almost around 40 to 50 pages. let me know if you found any thing that can help. this issue is only for some pdf , as most of the PDF are working fine.

**Comment by SaurabhPrajapati** [comment]
I am getting this crash only while adding subview's(aka forms) more than 126!

**Comment by SaurabhPrajapati** [comment]
Using WKWebview instead of UIWebView Solved my problem!
