### ISSUE TITLE
Change Form Text Field Font Size

### ISSUE THREAD

**Issue by calvinlau717** [derekblair/ILPDFKit#39]
I have a form in my project, and this form has some textfield. I modify the textfield using follow code and this works:

document.forms.setValue( "Name", forFormWithName: "LabourName")

However, i want to change the font size of the text field in the form , named "LabourName". I have tried to change the font size of the form to 16 in the PDF, but when i set the text field in the form using above code, the font size still remain unchanged. How can i modify the font size or other property like bold words in text field?  Thanksss.

**Comment by codicil** [comment]
@calvinlau717 did you find answer to your question, would you like to share

**Comment by calvinlau717** [comment]
@codicil I can't find the answer either.

**Comment by derekblair** [comment]
See `[ILPDFForm associatedWidget]` then on the resulting `ILPDFFormTextField` access the `UITextField` via  `textFieldOrTextView`. From there, you can customize it was you wish.
