### ISSUE TITLE
Fast Scrolling PDF - will showing forms on different page than original

### ISSUE THREAD

**Issue by SaurabhPrajapati** [derekblair/ILPDFKit#44]
while checking ILPDFKit framework/library with **WKWebView instead of UIWebView** will showing some textfields on diffrent page then expected page while fast scrolling through PDF.

**Comment by SaurabhPrajapati** [comment]
Set pagingEnable of Scrollview solve my Problem

**Comment by derekblair** [comment]
Should be resolved in 1.1.3 and after.
