### ISSUE TITLE
Closing app with an open ILPDFViewController displays blank PDF on re-entry.

### ISSUE THREAD

**Issue by chucktee** [derekblair/ILPDFKit#45]
If you are viewing a PDF, close the app with the Home button, then re-open the app- the PDF will change to a split half-black half-white screen.

It appears the app reopen flow calls into ILPDFViewController 
calls
- (void)viewWillTransitionToSize
which calls 
[self loadPDFView];
which creates a new _pdfView = [[ILPDFView alloc] initWithDocument:_document];
then adds it to the view with-
[self.view addSubview:_pdfView];

Which I assume is causing the blank.

If I change the function to:

```
- (void)loadPDFView {
    [_pdfView removeFromSuperview];
    if (!_pdfView) {
        _pdfView = [[ILPDFView alloc] initWithDocument:_document];
    }
    [self.view addSubview:_pdfView];
}
```

It works.

Is it my implementation causing an issue?  Or is this a viable fix.

Thanks for your work.

**Comment by derekblair** [comment]
fixed in aee473280c0b72f8542eee9d1b70815438ef9113
