### ISSUE TITLE
Internal navigation is not Working Properly

### ISSUE THREAD

**Issue by SaurabhPrajapati** [derekblair/ILPDFKit#47]
Hi , 
**I have found below issue in latest updated ILPDFKit**

While jump to page 10 from page 1 , interactive Elements are not showing.
Ex. while navigating to 10th page it shows the elements of 5th page.

Navigating single page works fine.

**Comment by SaurabhPrajapati** [comment]
changing below line solved my problem

[_pdfPages setObject:sv forKey:@([_pageYValues indexOfObject:@(yVal)]+1)];

to 

int page = (int)(sv.frame.origin.y/sv.frame.size.height) + 1;
            
            [_pdfPages setObject:sv forKey:@(page)];

This is because if i am redirected to 10th page but still my array of _pdfPages contains only 4 objects , so indexOfObject:sv return 5 instead of 10.Please update this in ILPDFKit.

**Comment by derekblair** [comment]
Thanks fixed in 1.1.6
