### ISSUE TITLE
Black bars appear with 1.1.3

### ISSUE THREAD

**Issue by MauriceHmb** [derekblair/ILPDFKit#49]
I found a new issue using 1.1.3, the latest update. The Viewer has black bars at the left and right border. I also tried another pdf file, but stil the same. See the screenshots below:

Version 1.1.1
![bildschirmfoto 2017-03-01 um 22 14 00](https://cloud.githubusercontent.com/assets/23486283/23495013/a1145696-ff16-11e6-867b-ce63e814542f.jpg)

Version 1.1.3 
![bildschirmfoto 2017-03-01 um 22 12 39](https://cloud.githubusercontent.com/assets/23486283/23495014/a1150b18-ff16-11e6-9e0c-9674a5cfb1af.jpg)

**Comment by derekblair** [comment]
fixed in 1.1.6

**Comment by MauriceHmb** [comment]
Black bars now changed to white bars! The bars are still there

**Comment by derekblair** [comment]
@MauriceHmb Please see `[ILPDFViewController applyConstraintsToPDFView] ` to readjust the constraints to meet your needs.
