### ISSUE TITLE
Forms not showing for "Some kind of editable PDF"s 

### ISSUE THREAD

**Issue by yasirmturk** [derekblair/ILPDFKit#50]
I have here some special kind of editable PDF which is editable in Preview app and other desktop apps (also on windows) but shown as read-only through this library.. can u suggest whats the issue?
<img width="833" alt="itext_pdf__1_page_" src="https://cloud.githubusercontent.com/assets/306691/24101753/48b61cda-0d9b-11e7-85fd-ee051cb18c61.png">
[itext.pdf](https://github.com/derekblair/ILPDFKit/files/855083/itext.pdf)

**Comment by yasirmturk** [comment]
No form is shown in the app 
![simulator screen shot 20-mar-2017 6 28 11 pm](https://cloud.githubusercontent.com/assets/306691/24101895/cfa45298-0d9b-11e7-9bcd-2d61265a818a.png)

**Comment by derekblair** [comment]
thanks @yasirmturk I will investigate and fix this asap.

**Comment by yasirmturk** [comment]
much appreciated

**Comment by derekblair** [comment]
It appears @yasirmturk that the file in question is lacking AcroForms, but instead has simple line annotations.
