### ISSUE TITLE
App crash because createWidgetAnnotationViewForPageView returns nil

### ISSUE THREAD

**Issue by Barnalite** [derekblair/ILPDFKit#52]
Hi,

If the form has the ILPDFAnnotationFlagHidden, ILPDFAnnotationFlagInvisible o ILPDFAnnotationFlagNoView, createWidgetAnnotationViewForPageView returns nil. Later, the method updateWidgetAnnotationViews tries to add this nil view and add it to an array. The app crashes. Found using a pdf with those flags.

Thanks

Guillem

**Comment by derekblair** [comment]
fixed in 1.1.6
