### ISSUE TITLE
Abandon Ware?

### ISSUE THREAD

**Issue by perlmunger** [derekblair/ILPDFKit#74]
I downloaded the iOS 10.3 simulator and form field editing still works there, but iOS 12 and 13 (Haven't tried 11 yet) you can't edit any longer. Anyhow, just posting this here so that others aren't wondering if it should be working in iOS 13+. It doesn't currently. Thanks.

**Comment by psirigiano** [comment]
Any update?

**Comment by derekblair** [comment]
Fixed in 2.0.0
