### ISSUE TITLE
PDF not editable?

### ISSUE THREAD

**Issue by ntfchris** [derekblair/ILPDFKit#75]
I downloaded the demo app but cannot find the way to make the PDF editable, it is still read only.
Anybody can help?

**Comment by Ibrahimarain** [comment]
Same happening to me. :(

**Comment by psirigiano** [comment]
Any solutions for this?

**Comment by psirigiano** [comment]
Does anyone have an example on how to fix this?  I see some mentions of a solution but any example on how to do this?

"Hi, we can use the Apple's PDFView to render the pdf and then after completing the form, we can again convert that pdf to ILPDFKit document by initialising the ilpdfDocument with data using "pdfView.document.dataRepresentation]" (to use all the other features of ILPDFKit such as extracting form values)."

**Comment by derekblair** [comment]
resolved in 2.0.0
